language: node_js
node_js:
    - "node"
install:
    - "npm i"
script:
    - "npm run build"
deploy:
    provider: s3
    access_key_id: $AWS_KEY_ID
    secret_access_key:
        secure: $AWS_SECRET_KEY
    bucket: $AWS_BUCKET
    region: $AWS_REGION
    skip_cleanup: true
    local-dir: build
    on:
        branch: master
