language: node_js
node_js:
- node
env:
- NODE_ENV=production
cache: pip
before_install:
- npm i -g npm@latest
- sudo apt-get install build-essential
- sudo apt-get install libgmp-dev
install:
- npm i
script:
- npm run build
before_deploy:
- pip install awscli --user
deploy:
  provider: s3
  access_key_id: $AWS_ACCESS_KEY_ID
  secret_access_key: $AWS_SECRET_ACCESS_KEY
  bucket: swapwatch.io
  region: $AWS_DEFAULT_REGION
  acl: public_read
  skip_cleanup: true
  local-dir: build
  on:
    branch: master
after_deploy:
- aws configure set preview.cloudfront true
- aws cloudfront create-invalidation --distribution-id $CLOUDFRONT_DISTRIBUTION_ID --paths "/*"
